import numpy as np
import matplotlib.pyplot as plt
x=np.arange(0,100)
y=x*2
z=x**2
# plt.show()
# fig=plt.figure()
# ax=fig.add_axes([0,0,1,1])
# ax.plot(x,y)
# ax.set_xlabel('X')
# ax.set_ylabel('Y')
# ax.set_title('title')
# plt.show()
# ax1=fig.add_axes([0,0,1,1])
# ax2=fig.add_axes([0.2,0.5,.2,.2])
# ax1.plot(x,y)
# ax2.plot(x,y)
# plt.show()
# ax3=fig.add_axes([0,0,1,1])
# ax4=fig.add_axes([0.2,0.5,.4,.4])
# ax5=fig.add_axes([0,0,1,1])
# ax6=fig.add_axes([0.2,0.5,.4,.4])
# ax6.set_xlim([20,22])
# ax6.set_ylim([30,50])
# ax5.plot(x,z)
# ax6.plot(x,y)
# ax5.set_xlabel('X')
# ax5.set_ylabel('Z')
# ax6.set_xlabel('X')
# ax6.set_ylabel('Y')
# ax6.set_title('ZOOM')
fig, ax=plt.subplots(nrows=1,ncols=2,figsize=(12,3))
ax[0].plot(x,y,'b--',lw=2)
ax[1].plot(x,z,'r',lw=2)
plt.tight_layout()
plt.show()