from os import name
import pandas as pd
df=pd.read_csv('D:/Autormt°/Courses/Data Visualization/[DesireCourse.Net] Udemy - Python for Data Science and Machine Learning Bootcamp/1. Course Introduction\Refactored_Py_DS_ML_Bootcamp-master/04-Pandas-Exercises/Salaries.csv')
# print(df)
# print(df.head())
# df.info()
# print(df[['BasePay']].mean())
# print(df[['OvertimePay']].max())
# print(df[(df['EmployeeName']=='JOSEPH DRISCOLL')]['JobTitle'])
# print(df[(df['EmployeeName']=='JOSEPH DRISCOLL')]['TotalPayBenefits'])
# print(df[df['TotalPayBenefits']==df['TotalPayBenefits'].max()])
# print(df[df['TotalPayBenefits']==df['TotalPayBenefits'].min()])
# print(df.groupby('Year')['BasePay'].mean())
# print(df['JobTitle'].unique())
# print(df['JobTitle'].nunique())
# print(df['JobTitle'].value_counts().head(5))
# print(sum(df[df['Year'] == 2013]['JobTitle'].value_counts()==1))
# def chief_str(nom):
#     if 'chief' in nom.lower():
#         return True
#     else:
#         return False
# print(sum(df['JobTitle'].apply(lambda x: chief_str(x))))
# df['title_len']=df['JobTitle'].apply(len)
# print(df[['title_len','TotalPayBenefits']].corr()
# )
ecom=pd.read_csv('D:/Autormt°/Courses/Data Visualization/[DesireCourse.Net] Udemy - Python for Data Science and Machine Learning Bootcamp/1. Course Introduction\Refactored_Py_DS_ML_Bootcamp-master/04-Pandas-Exercises/Ecommerce Purchases')
# print(ecom.head())
# print(ecom.info())
# print(ecom['Purchase Price'].mean())
# print(ecom['Purchase Price'].max())
# print(ecom['Purchase Price'].min())
# print(sum(ecom['Language']=='en'))
# print(ecom[ecom['Language']=='en'].count())
# print(sum(ecom['Job']=='Lawyer'))
# print(ecom[ecom['Job']=='Lawyer'].info())
# print((ecom['AM or PM']=='AM').value_counts())
# print((ecom['AM or PM']).value_counts())
# print(ecom['Job'].value_counts().head(5))
# print(ecom[ecom['Lot']=='90 WT']['Purchase Price'])
# print(ecom[ecom['Credit Card']==4926535242672853]['Email'])
# print(ecom[(ecom['CC Provider']=='American Express') & (ecom['Purchase Price']>95)].count())
# print((ecom[(ecom['CC Exp Date']>='01/25') & (ecom['CC Exp Date']<='12/25')]).count())
# print(sum(ecom['CC Exp Date'].apply(lambda x:x[3:]=='25')))
# print(ecom['Email'].apply(lambda x: x.split('@')[1]).value_counts().head(5))
